steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/tt-dev-001/colorful-weather-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/tt-dev-001/colorful-weather-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'colorful-weather-app'
      - '--image'
      - 'gcr.io/tt-dev-001/colorful-weather-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'  # Replace with the desired region
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/colorful-weather-app'
